import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'see_all': 'See All',
      'popular_product': 'Popular Product',
      'categories': 'Categories',
      'search_hint': 'Search..',
      'home_catalogs_title': 'Catalogs for You',
      'greeting_title': 'Hello {name},',
      'greeting_subtitle': 'Good Morning!',
      'default_user_name': 'Guest',
      'promo_title': 'Get Your Special Sale Up to 40%',
      'promo_cta': 'Shop Now',
      'shopping_banner_title': '40% off on the new season arrivals',
      'search': 'Search',
      'wishlist_empty_title': 'No favorites yet',
      'wishlist_empty_subtitle': 'Add items to wishlist from product pages',
      'add_to_cart': 'Add To Cart',
      'added_to_cart': 'Added to cart',
      'added_opening_cart': 'Added and opening cart',
      'buy_now': 'Buy Now',
      'cart_title': 'My Cart',
      'discount_code_hint': 'Enter Discount Code',
      'apply': 'Apply',
      'checkout': 'Checkout',
      'checkout_title': 'Checkout',
      'shipping_address': 'Shipping Address',
      'payment_method': 'Payment Method',
      'order_summary': 'Order Summary',
      'order_empty_cart_message': 'Your cart is empty. Add items before checking out.',
      'place_order': 'Place Order',
      'edit': 'Edit',
      'edit_address': 'Edit Address',
      'edit_payment': 'Edit Payment',
      'name_label': 'Full Name',
      'phone_label': 'Phone Number',
      'street_label': 'Street Address',
      'city_label': 'City',
      'country_label': 'Country',
      'payment_brand_label': 'Card Brand',
      'payment_last4_label': 'Last 4 Digits',
      'save_changes': 'Save Changes',
      'form_incomplete_message': 'Please complete all fields.',
      'account': 'Account',
      'settings': 'Settings',
      'support': 'Support',
      'orders_title': 'My Orders',
      'order_id_label': 'Order #{id}',
      'placed_on': 'Placed on',
      'order_more_items': '+{count} more items',
      'order_status_processing': 'Processing',
      'order_status_completed': 'Completed',
      'orders_empty_title': 'No orders yet',
      'orders_empty_subtitle': 'Place your first order to see it here.',
      'order_success_title': 'Order Confirmed!',
      'order_success_subtitle': 'Order {id} has been placed successfully.',
      'view_orders': 'View Orders',
      'continue_shopping': 'Continue Shopping',
      'filters': 'Filters',
      'reset': 'Reset',
      'gender': 'Gender',
      'category': 'Category',
      'price_range': 'Price Range',
      'no_results': 'No results found',
      'wishlist': 'My Wishlist',
      'cart_empty': 'Your cart is empty',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'total': 'Total',
      'product_not_found': 'Product not found',
      'details': 'Details',
      'select_size': 'Select Size',
      'quantity': 'Quantity',
      'description': 'Description',
      'please_select_size': 'Please select a size',
      'onboarding_skip': 'Skip',
      'onboarding_next': 'Next',
      'onboarding_get_started': 'Get Started',
      'onboarding_title_1': 'Discover the Latest Trends',
      'onboarding_subtitle_1': 'Browse curated collections tailored to your unique style.',
      'onboarding_title_2': 'Wishlist Your Favorites',
      'onboarding_subtitle_2': 'Save pieces you love and keep track of new drops instantly.',
      'onboarding_title_3': 'Fast & Secure Checkout',
      'onboarding_subtitle_3': 'Enjoy a seamless shopping journey with secure payment options.',
      'login_title': 'Sign In',
      'login_subtitle': 'Welcome back! Enter your details to access your account.',
      'welcome_back': 'Welcome back 👋',
      'login_button': 'Continue',
      'login_create_account': 'Create a new account',
      'register_title': 'Create Account',
      'register_heading': 'Join the community',
      'register_subtitle': 'Sign up to track orders, wishlist products, and more.',
      'register_button': 'Sign Up',
      'register_have_account': 'Already have an account? Sign in',
      'confirm_password_label': 'Confirm Password',
      'validation_required': 'This field is required',
      'validation_email': 'Enter a valid email address',
      'validation_password_length': 'Password must be at least 6 characters',
      'validation_password_match': 'Passwords do not match',
      'validation_name_length': 'Name should be at least 3 characters',
      'auth_welcome_back': 'Signed in successfully',
      'auth_account_created': 'Account created! Welcome aboard.',
      'auth_generic_error': 'Something went wrong. Please try again.',
      'auth.invalid_credentials': 'Incorrect email or password',
      'auth.email_in_use': 'This email is already registered',
      'auth.invalid_password': 'Current password is incorrect',
      'appearance': 'Appearance',
      'language': 'Language',
      'language_english': 'English',
      'language_arabic': 'Arabic',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_system': 'System',
      'account_settings': 'Account Settings',
      'app_preferences': 'App Preferences',
      'notifications_settings': 'Notifications',
      'push_notifications': 'Push Notifications',
      'email_notifications': 'Email Alerts',
      'offers_notifications': 'Offers & Promotions',
      'contact_us': 'Contact Us',
      'support_placeholder': 'Support chat is coming soon.',
      'profile_updated': 'Profile updated successfully',
      'password_updated': 'Password updated successfully',
      'email_label': 'Email',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'size_label': 'Size',
      'quantity_short': 'Qty',
      'logout': 'Log Out',
      'logout_success': 'You have been signed out',
    },
    'ar': {
      'see_all': 'شاهد الكل',
      'popular_product': 'المنتجات الرائجة',
      'categories': 'الفئات',
      'search_hint': 'ابحث..',
      'home_catalogs_title': 'كتالوجات لأجلك',
      'greeting_title': 'مرحباً {name},',
      'greeting_subtitle': 'صباح الخير!',
      'default_user_name': 'زائر',
      'promo_title': 'احصل على خصم خاص يصل إلى 40%',
      'promo_cta': 'تسوق الآن',
      'shopping_banner_title': 'خصم 40٪ على تشكيلة الموسم الجديد',
      'search': 'بحث',
      'wishlist_empty_title': 'لا مفضلات بعد',
      'wishlist_empty_subtitle': 'أضف عناصر للمفضلة من صفحة المنتجات',
      'add_to_cart': 'أضف إلى السلة',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'added_opening_cart': 'تمت الإضافة وسيتم فتح السلة',
      'buy_now': 'اشتري الآن',
      'cart_title': 'سلتي',
      'discount_code_hint': 'أدخل رمز الخصم',
      'apply': 'تطبيق',
      'checkout': 'إتمام الشراء',
      'checkout_title': 'إتمام الشراء',
      'shipping_address': 'عنوان التوصيل',
      'payment_method': 'طريقة الدفع',
      'order_summary': 'ملخص الطلب',
      'order_empty_cart_message': 'سلتك فارغة، أضف منتجات للمتابعة.',
      'place_order': 'تأكيد الطلب',
      'edit': 'تعديل',
      'edit_address': 'تعديل العنوان',
      'edit_payment': 'تعديل الدفع',
      'name_label': 'الاسم الكامل',
      'phone_label': 'رقم الهاتف',
      'street_label': 'عنوان الشارع',
      'city_label': 'المدينة',
      'country_label': 'الدولة',
      'payment_brand_label': 'شركة البطاقة',
      'payment_last4_label': 'آخر 4 أرقام',
      'save_changes': 'حفظ التعديلات',
      'form_incomplete_message': 'يرجى إكمال جميع الحقول.',
      'account': 'الحساب',
      'settings': 'الإعدادات',
      'support': 'الدعم',
      'orders_title': 'طلباتي',
      'order_id_label': 'طلب #{id}',
      'placed_on': 'تاريخ الطلب',
      'order_more_items': '+{count} عناصر إضافية',
      'order_status_processing': 'قيد المعالجة',
      'order_status_completed': 'مكتمل',
      'orders_empty_title': 'لا توجد طلبات بعد',
      'orders_empty_subtitle': 'عند إتمام عملية شراء ستظهر هنا.',
      'order_success_title': 'تم تأكيد الطلب!',
      'order_success_subtitle': 'تم إرسال طلب {id} بنجاح.',
      'view_orders': 'عرض الطلبات',
      'continue_shopping': 'متابعة التسوق',
      'filters': 'التصفية',
      'reset': 'إعادة ضبط',
      'gender': 'الجنس',
      'category': 'الفئة',
      'price_range': 'نطاق السعر',
      'no_results': 'لا توجد نتائج',
      'wishlist': 'قائمة المفضلة',
      'cart_empty': 'سلتك فارغة',
      'subtotal': 'الإجمالي الفرعي',
      'discount': 'الخصم',
      'total': 'الإجمالي',
      'product_not_found': 'المنتج غير موجود',
      'details': 'التفاصيل',
      'select_size': 'اختر المقاس',
      'quantity': 'الكمية',
      'description': 'الوصف',
      'please_select_size': 'يرجى اختيار المقاس',
      'onboarding_skip': 'تخطي',
      'onboarding_next': 'التالي',
      'onboarding_get_started': 'ابدأ الآن',
      'onboarding_title_1': 'اكتشف أحدث الصيحات',
      'onboarding_subtitle_1': 'تصفح مجموعات منسقة تناسب ذوقك الخاص.',
      'onboarding_title_2': 'أضف المفضلات لقائمتك',
      'onboarding_subtitle_2': 'احفظ القطع التي تحبها وتابع الإصدارات الجديدة فوراً.',
      'onboarding_title_3': 'دفع سريع وآمن',
      'onboarding_subtitle_3': 'استمتع بتجربة تسوق سلسة مع خيارات دفع آمنة.',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'مرحباً بعودتك! أدخل بياناتك للوصول إلى حسابك.',
      'welcome_back': 'أهلاً بعودتك 👋',
      'login_button': 'متابعة',
      'login_create_account': 'إنشاء حساب جديد',
      'register_title': 'إنشاء حساب',
      'register_heading': 'انضم إلى مجتمعنا',
      'register_subtitle': 'سجل لتتبع الطلبات، وحفظ المفضلات، وأكثر.',
      'register_button': 'تسجيل',
      'register_have_account': 'لديك حساب؟ قم بتسجيل الدخول',
      'confirm_password_label': 'تأكيد كلمة المرور',
      'validation_required': 'هذا الحقل مطلوب',
      'validation_email': 'أدخل بريدًا إلكترونيًا صالحًا',
      'validation_password_length': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'validation_password_match': 'كلمتا المرور غير متطابقتين',
      'validation_name_length': 'يجب أن لا يقل الاسم عن 3 أحرف',
      'auth_welcome_back': 'تم تسجيل الدخول بنجاح',
      'auth_account_created': 'تم إنشاء الحساب بنجاح!',
      'auth_generic_error': 'حدث خطأ ما، حاول مرة أخرى.',
      'auth.invalid_credentials': 'البريد أو كلمة المرور غير صحيحة',
      'auth.email_in_use': 'هذا البريد مسجل مسبقاً',
      'auth.invalid_password': 'كلمة المرور الحالية غير صحيحة',
      'appearance': 'المظهر',
      'language': 'اللغة',
      'language_english': 'الإنجليزية',
      'language_arabic': 'العربية',
      'theme_light': 'فاتح',
      'theme_dark': 'داكن',
      'theme_system': 'حسب النظام',
      'account_settings': 'إعدادات الحساب',
      'app_preferences': 'تفضيلات التطبيق',
      'notifications_settings': 'الإشعارات',
      'push_notifications': 'إشعارات الدفع',
      'email_notifications': 'تنبيهات البريد الإلكتروني',
      'offers_notifications': 'عروض وترقيات',
      'contact_us': 'تواصل معنا',
      'support_placeholder': 'سيتم توفير خدمة الدعم قريباً.',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح',
      'password_updated': 'تم تحديث كلمة المرور بنجاح',
      'email_label': 'البريد الإلكتروني',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'size_label': 'المقاس',
      'quantity_short': 'الكمية',
      'logout': 'تسجيل الخروج',
      'logout_success': 'تم تسجيل الخروج بنجاح',
    },
  };

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
